/*
 * Clean Code API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace APIClient.Model
{
    /// <summary>
    /// Defines OrderStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderStatus
    {
        /// <summary>
        /// Enum NotStarted for value: NotStarted
        /// </summary>
        [EnumMember(Value = "NotStarted")]
        NotStarted = 1,

        /// <summary>
        /// Enum OnHold for value: OnHold
        /// </summary>
        [EnumMember(Value = "OnHold")]
        OnHold = 2,

        /// <summary>
        /// Enum OnGoing for value: OnGoing
        /// </summary>
        [EnumMember(Value = "OnGoing")]
        OnGoing = 3,

        /// <summary>
        /// Enum Finished for value: Finished
        /// </summary>
        [EnumMember(Value = "Finished")]
        Finished = 4

    }

}
